# syntax=docker/dockerfile:1.7

# ------------------------------------------------------------
# Rivqo Website - production Dockerfile
#
# Multi-stage build using Next.js standalone output.
# Final image size: ~150MB (vs ~1GB without standalone).
#
# Build:   docker build -t rivqo-website .
# Run:     docker run --rm -p 3000:3000 rivqo-website
# ------------------------------------------------------------

ARG NODE_VERSION=20.18-alpine

# ============================================================
# Stage 1: install dependencies (cached by package*.json hash)
# ============================================================
FROM node:${NODE_VERSION} AS deps

# libc6-compat is required by some native Node modules on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy only manifest files first so the dep layer is cached
# as long as dependencies don't change.
COPY package.json package-lock.json* ./

# Use npm ci for reproducible installs from package-lock.json.
# --ignore-scripts skips lifecycle scripts during install for security.
RUN npm ci --ignore-scripts


# ============================================================
# Stage 2: build the Next.js app
# ============================================================
FROM node:${NODE_VERSION} AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build produces .next/standalone and .next/static
RUN npm run build


# ============================================================
# Stage 3: minimal runtime image
# ============================================================
FROM node:${NODE_VERSION} AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Create a non-root user to run the app
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy public assets (served as static files by Next.js)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Standalone build outputs a minimal server with only the required deps
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# Basic container health check - hits the homepage every 30s.
# Requires no extra tooling because Node ships with fetch.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"

# server.js is the entrypoint generated by Next.js standalone output
CMD ["node", "server.js"]
